import { ShieldCheck } from "lucide-react";

export function AiDisclaimer({ className = "" }: { className?: string }) {
  return (
    <div
      className={`flex items-start gap-3 rounded-xl border border-border bg-muted/60 p-4 text-sm text-muted-foreground ${className}`}
    >
      <ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" />
      <p>
        <span className="font-medium text-foreground">Responsible AI:</span> outputs are generated by
        AI and may be inaccurate or incomplete. Review and edit everything before sending, and never
        paste confidential or personal data you are not permitted to share.
      </p>
    </div>
  );
}
